// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const base = {
  'components.molecules.MarkersLayout.tooltip.showOnGoogleMaps':
    'Показать на Google Картах',

  'components.organisms.Filters.filters.empty': 'Без категории',
  'components.organisms.Filters.filters.old_town': 'Старинные поселения',
  'components.organisms.Filters.filters.fortress': 'Форты и крепости',
  'components.organisms.Filters.filters.palace': 'Дворцы',
  'components.organisms.Filters.filters.christian': 'Часовни и монастыри',
  'components.organisms.Filters.filters.cave': 'Пещеры',
  'components.organisms.Filters.filters.waterfall': 'Водопады',
  'components.organisms.Filters.filters.nature':
    'Озера, парки и природные зоны',
  'components.organisms.Filters.filters.lighthouse': 'Маяки',
  'components.organisms.Filters.filters.bridge': 'Мосты',
  'components.organisms.Filters.filters.monument': 'Монументы и памятники',
  'components.organisms.Filters.filters.other': 'Разное',
  'components.organisms.Filters.subLabel.0': 'нет локаций',
  'components.organisms.Filters.subLabel.1': '{count} локация',
  'components.organisms.Filters.subLabel.2': '{count} локации',
  'components.organisms.Filters.subLabel.3': '{count} локаций',

  'components.organisms.MapView.filters': 'Фильтры',
  'components.organisms.MapView.filters.0': 'ничего не выбрано',
  'components.organisms.MapView.filters.1': '{to} локация из {from}',
  'components.organisms.MapView.filters.2': '{to} локации из {from}',
  'components.organisms.MapView.filters.3': '{to} локаций из {from}',
};
