// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const base = {
  'components.molecules.Map.tooltip.showOnGoogleMaps':
    'Показать на Google Картах',

  'components.organisms.Filters.filters.empty': 'Без категории',
  'components.organisms.Filters.filters.old_town': 'Старинные поселения',
  'components.organisms.Filters.filters.fortress': 'Форты и крепости',
  'components.organisms.Filters.filters.cave': 'Пещеры',
  'components.organisms.Filters.filters.lighthouse': 'Маяки',
  'components.organisms.Filters.filters.monument': 'Монументы',
  'components.organisms.Filters.filters.ruin': 'Руины',
  'components.organisms.Filters.filters.historical': 'Разное историческое',
  'components.organisms.Filters.filters.natural': 'Разное природное',

  'components.organisms.MapView.filters': 'Фильтры',
  'components.organisms.MapView.filters.0': 'Ничего не выбрано',
  'components.organisms.MapView.filters.1': '{to} точка из {from}',
  'components.organisms.MapView.filters.2': '{to} точки из {from}',
  'components.organisms.MapView.filters.3': '{to} точек из {from}',
};
