name: jsnake

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  validate_code:
    name: Validate code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run prettier check
        run: yarn run prettier

      - name: Run linter
        run: yarn run lint

      - name: Run unit tests
        run: yarn run test
